services:
  - type: web
    name: sipat-quiz-friozem
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_PASSCODE
        sync: false
